### ISSUE TITLE
Display Model System

### ISSUE THREAD

**Issue by JamesVaughan** [TravelModellingGroup/XTMF2.Web#14]
- [ ] Display a Node #7
- [ ] Display a Start Node #8 
- [ ] Display a Link Between Nodes #9 
- [ ] Display a Disabled Node #10 
- [ ] Display a Disabled Link #11 
- [ ] Display the current Boundary #12 
- [ ] Display Simple Parameters #13
